beertwit/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

from beertwit import settings

urlpatterns = [
    url(r'^btwn/', include('btwn.urls')),
    url(r'^admin/', admin.site.urls)
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'btwn.views.page_not_found_404'

btwn/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^private$', views.HomeFeedView.as_view(), name='private_feed'),
    url(r'^profile/(?P<pk>[0-9]+)$', views.profile_feed, name='profile_feed'),
    url(r'^$', views.PublicFeed.as_view(), name='public_feed'),

    url(r'^post/create$', views.post_create_view, name='post_create'),
    url(r'^post/(?P<pk>[0-9]+)/$', views.PostDetailView.as_view(), name='post_detail'),
    url(r'^post/(?P<post_id>[0-9]+)/edit$', views.post_edit_view, name='post_edit'),
    url(r'^post/(?P<pk>[0-9]+)/delete$', views.PostDeleteView.as_view(), name='post_delete'),
    url(r'^post/(?P<post_id>[0-9]+)/comment$', views.comment_create_view, name='comment_create'),

    url(r'^comment/(?P<pk>[0-9]+)$', views.CommentDetailView.as_view(), name='comment_detail'),
    url(r'^comment/(?P<pk>[0-9]+)/edit$', views.comment_edit_view, name='comment_edit'),
    url(r'^comment/(?P<pk>[0-9]+)/delete$', views.CommentDeleteView.as_view(), name='comment_delete'),

    url(r'^register$', views.register_view, name='register'),
    url(r'^login$', views.login_view, name='login'),
    url(r'^logout$', views.logout_view, name='logout'),

    url(r'^follow/(?P<pk>[0-9]+)$', views.follow, name='follow'),
    url(r'^unfollow/(?P<pk>[0-9]+)$', views.unfollow, name='unfollow')
]

app_name = 'btwn'

btwn/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError

from .models import UserProfile, Post, Comment


class UserForm(forms.ModelForm):
    password_confirmation = forms.CharField(max_length=20, required=True)

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password']

    def clean_password_confirmation(self):
        confirmation = self.cleaned_data['password_confirmation']
        password = self.cleaned_data['password']
        if confirmation != password:
            raise ValidationError('Passwords do not match')
        return confirmation

    def clean_username(self):
        data = self.cleaned_data['username']
        if User.objects.filter(username=data).exists():
            raise ValidationError('Username already taken.')
        return data


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile

        fields = ['profile_name']

    def clean_profile_name(self):
        data = self.cleaned_data['profile_name']
        if UserProfile.objects.filter(profile_name=data).exists():
            raise ValidationError("Profile name already taken")
        return data


class LoginForm(forms.Form):
    login = forms.CharField(label='User name', max_length=100, required=True)
    password = forms.CharField(label='Your password', max_length=100, required=True)


class CommentCreateForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['comment_text']


class PostCreateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'post_text', 'public', 'image']

beertween/templates/beertween/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'beertween:vote' question.id %}" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}"/>
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br/>
    {% endfor %}
    <input type="submit" value="Vote"/>
</form>

btwn/templates/btwn/base_generic.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link type="text/css" rel="stylesheet" href="{% static 'btwn/materialize/css/materialize.min.css' %}"
          media="screen,projection"/>
    <link type="text/css" rel="stylesheet" href="{% static 'btwn/btwn-styles.css' %}"/>
    <title>Beertweet</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
</head>

<body>
<script src="{% static 'btwn/jquery-2.1.4.js' %}"></script>
<script type="text/javascript" src="{% static 'btwn/materialize/js/materialize.min.js' %}"></script>

{% load btwn_filters %}
{% block navbar %}

    <nav>
        <div class="nav-wrapper">
            <a href="#" class="brand-logo right">BeerTween</a>
            <ul id="nav-mobile" class="left hide-on-med-and-down">
                <li><a href="{% url 'btwn:public_feed' %}">Public Feed</a></li>
                {% if user.is_authenticated %}
                    <li><a href="{% url 'btwn:private_feed' %}">Private Feed</a></li>
                    <li><a href="{% url 'btwn:post_create' %}">Add pint</a></li>
                    <li><a href="{% url 'btwn:profile_feed' user.id %}">{{ user | profile_name }}</a></li>
                    <li><a href="{% url 'btwn:logout' %}">Logout</a></li>
                {% else %}
                    <li><a href="{% url 'btwn:login' %}">Login</a></li>
                    <li><a href="{% url 'btwn:register' %}">Register</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>
{% endblock %}
<div class="container">
    <div class="row">
        <h4 class="center-align">{% block title %}
            Beertweet
        {% endblock %}</h4>

        <div class="col s12">
            {% block content %}{% endblock %}
        </div>
    </div>
</div>
</body>
</html>

btwn/templates/btwn/comment_confirm_delete.html
{% extends 'btwn/base_generic.html' %}
{% block title %}
    Deleting Comment
{% endblock %}
{% block content %}
    <form action="" method="post">{% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}"?</p>
        <input type="submit" value="Confirm"/>
    </form>
{% endblock %}

btwn/templates/btwn/comment_create.html
{% extends 'btwn/base_generic.html' %}
{% block title %}
    Creating a comment
{% endblock %}
{% block content %}
    <form action="" method="post" e>
        {% csrf_token %}
        {% load materializecss %}
        {{ form | materializecss }}
        <div class="center-align"><input type="submit" value="Create"
                                         class="waves-effect waves-light btn red btwn-button"/></div>
    </form>
{% endblock %}

btwn/templates/btwn/comment_detail.html
{% extends 'btwn/base_generic.html' %}
{% block title %}
    {{ comment.author.profile_name }}'s comment
{% endblock %}
{% block content %}
    <div class="z-depth-1 comment-tab hoverable">
        <b><a href="{% url 'btwn:profile_feed' comment.author.user.id %}">
            {{ comment.author.profile_name }}</a></b>
        <span>on {{ comment.created_on | date:"Y-M-d" }}</span>
        <a href="{% url 'btwn:comment_detail' comment.id %}" class="ignore-link">
            <p>{{ comment.comment_text }}</p>
        </a>
        {% if is_author %}
            <div class="center-align"><a href="{% url 'btwn:comment_edit' comment.id %}"
                                         class="waves-effect waves-light btn red btwn-button">edit
                comment</a>
                <a href="{% url 'btwn:comment_delete' comment.id %}"
                   class="waves-effect waves-light btn red btwn-button">delete
                    comment</a></div>
        {% else %}
        {% endif %}
    </div>
{% endblock %}

btwn/templates/btwn/comment_list.html
<div class="center-align"><a href="{% url 'btwn:comment_create' post.id %}"
                             class="waves-effect waves-light btn red btwn-button">
    Add new comment</a></div>
{% for comment in post.comment_set.all %}
    <div class="z-depth-1 comment-tab hoverable">
        <b><a href="{% url 'btwn:profile_feed' comment.author.user.id %}">
            {{ comment.author.profile_name }}</a></b>
        <a href="{% url 'btwn:comment_detail' comment.id %}" class="ignore-link">
            <p>{{ comment.comment_text }}</p>
        </a>
    </div>
{% endfor %}

btwn/templates/btwn/custom404.html
{% extends 'btwn/base_generic.html' %}

{% block title %}
    UPS!
{% endblock %}
{% block content %}
    <div class="center-align"><h1><b><strong>404</strong></b></h1>
        {% load static %}
        <img src="{% static 'btwn/sad-beer.jpg' %}" alt="">
        <p>Something went wrong!</p>
    </div>
{% endblock %}

btwn/templates/btwn/generic_feed.html
{% load btwn_filters %}
{% if feed %}
    {% for post in feed %}
        <div class="z-depth-2 post-tab">
            {% include 'btwn/post_element.html' %}
            {% include 'btwn/comment_list.html' %}
        </div>
    {% endfor %}
{% else %}
    <div class="center-align"><p> No pint's available</p>
        {% load static %}
        <img src="{% static 'btwn/sad-beer.jpg' %}" alt=""></div>
{% endif %}

btwn/templates/btwn/home_feed.html
{% extends 'btwn/base_generic.html' %}
{% load btwn_filters %}
{% block title %}{{ title }}{% endblock %}
{% block content %}

    <div class="center-align">
        <div class="chip">Following: {{ user_profile.following.all | length }} profiles</div>
    </div>
    {% include 'btwn/generic_feed.html' %}
{% endblock %}

btwn/templates/btwn/login.html
{% extends "btwn/base_generic.html" %}

{% block content %}

    <form method="post" action="">
        {% csrf_token %}
        {{ login_form.as_p }}
        <input type="submit" value="login"/>
    </form>

{% endblock %}

btwn/templates/btwn/post_confirm_delete.html
{% extends 'btwn/base_generic.html' %}
{% block title %}
    Deleting {{ object.post_title }}
{% endblock %}
{% block content %}
    <form action="" method="post">{% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}"?</p>
        <input type="submit" value="Confirm"/>
    </form>
{% endblock %}

btwn/templates/btwn/post_create.html
{% extends 'btwn/base_generic.html' %}
{% block title %}
    Adding a new post
{% endblock %}
{% load materializecss %}
{% block content %}
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ post_create_form.title |materializecss }}
        {{ post_create_form.post_text |materializecss }}
        {{ post_create_form.image|materializecss }}
        <div class="fieldWrapper">
            <div class="col s12">
                {{ post_create_form.public.errors }}
                {{ post_create_form.public }}
                <label for="id_public">Public</label>
            </div>
        </div>
        <div class="center-align"><input type="submit" value="Add post"
                                         class="waves-effect waves-light btn red btwn-button"/></div>
    </form>
{% endblock %}

btwn/templates/btwn/post_edit.html
{% extends 'btwn/base_generic.html' %}

{% block title %}
    Editing {{ post_title }}
{% endblock %}
{% block content %}
    {% load materializecss %}

    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.title |materializecss }}
        {{ form.post_text |materializecss }}
        {{ form.image |materializecss }}
        <div class="fieldWrapper">
            <div class="col s12">
                {{ form.public.errors }}
                {{ form.public }}
                <label for="id_public">Public</label>
            </div>
        </div>

        <div class="center-align"><input type="submit" value="Update"
                                         class="waves-effect waves-light btn red btwn-button"/></div>

    </form>
{% endblock %}

btwn/templates/btwn/post_element.html
<a href="{% url 'btwn:post_detail' post.id %}"><h5 class="center-align">{{ post.title }}</h5></a>

<p class="center-align">
    <a href="{% url 'btwn:profile_feed' post.author.user.id %}"><b>{{ post.author.profile_name }}</b>
    </a>
    <span>Created on: {{ post.created_on | date:"Y-M-d" }}</span></p>
<img class="responsive-img" src="{{ post.image.url }}" alt="{{ post.title }}">
<p class="flow-text">{{ post.post_text }}</p>
{% if is_author %}
    <div class="center-align">
        <a href="{% url 'btwn:post_edit' post.id %}" class="waves-effect waves-light btn red btwn-button">Edit post</a>
        <a href="{% url 'btwn:post_delete' post.id %}" class="waves-effect waves-light btn red btwn-button">Delete
            post</a>
    </div>
{% endif %}

btwn/templates/btwn/profile_element.html
<div class="center-align">
    {% load btwn_filters %}

    <div class="chip">
        followers: {{ user_profile.followers }}
    </div>
    <div class="chip">
        folowing: {{ user_profile.following.all | length }}
    </div>
    <div class="chip">
        Pints: {{ user_profile.post_set.all | length }}
    </div>
    <div class="chip">
        Joined: {{ user_profile.joined | date:"Y-M-d" }}
    </div>
</div>
<div class="center-align">
    {% if user.is_authenticated %}
        {% if  not is_self %}
            {% if following %}
                <a href="{% url 'btwn:unfollow' user_profile.user.id %}"
                   class="waves-effect waves-light btn red btwn-button down-10 top-20">
                    unfollow
                </a>
            {% else %}

                <a href="{% url 'btwn:follow' user_profile.user.id %}"
                   class="waves-effect waves-light btn red btwn-button down-10 top-20">
                    follow
                </a>
            {% endif %}
        {% endif %}
    {% endif %}
</div>